
package vpsicotropico.service.sngpc.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "sngpcSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SngpcSoap {


    /**
     * 
     * @param senha
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidarUsuario", action = "http://tempuri.org/ValidarUsuario")
    @WebResult(name = "ValidarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidarUsuario", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.ValidarUsuario")
    @ResponseWrapper(localName = "ValidarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.ValidarUsuarioResponse")
    public String validarUsuario(
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/")
        String senha);

    /**
     * 
     * @param senha
     * @param arq
     * @param hashIdentificacao
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaArquivoSNGPC", action = "http://tempuri.org/EnviaArquivoSNGPC")
    @WebResult(name = "EnviaArquivoSNGPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviaArquivoSNGPC", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.EnviaArquivoSNGPC")
    @ResponseWrapper(localName = "EnviaArquivoSNGPCResponse", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.EnviaArquivoSNGPCResponse")
    public String enviaArquivoSNGPC(
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/")
        String senha,
        @WebParam(name = "Arq", targetNamespace = "http://tempuri.org/")
        byte[] arq,
        @WebParam(name = "HashIdentificacao", targetNamespace = "http://tempuri.org/")
        String hashIdentificacao);

    /**
     * 
     * @param senha
     * @param cnpj
     * @param email
     * @param hash
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaDadosArquivoSNGPC", action = "http://tempuri.org/ConsultaDadosArquivoSNGPC")
    @WebResult(name = "ConsultaDadosArquivoSNGPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaDadosArquivoSNGPC", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.ConsultaDadosArquivoSNGPC")
    @ResponseWrapper(localName = "ConsultaDadosArquivoSNGPCResponse", targetNamespace = "http://tempuri.org/", className = "vpsicotropico.service.sngpc.wsdl.ConsultaDadosArquivoSNGPCResponse")
    public String consultaDadosArquivoSNGPC(
        @WebParam(name = "Email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/")
        String senha,
        @WebParam(name = "CNPJ", targetNamespace = "http://tempuri.org/")
        String cnpj,
        @WebParam(name = "Hash", targetNamespace = "http://tempuri.org/")
        String hash);

}
